import { Form } from './schemas'

// Form configurations for each entity type
export const formConfigs: Record<string, Form> = {
  project: {
    id: 'project',
    title: 'Project',
    description: 'Create or update a project',
    submitText: 'Save Project',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        required: true,
        placeholder: 'Enter project title',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'category',
        label: 'Category',
        type: 'select',
        required: false,
        validation: { minLength: 1 },
        options: [
          { label: 'AI Learning/Exploration', value: 'AI Learning/Exploration' },
          { label: 'Frontend/UI/UX', value: 'Frontend/UI/UX' },
          { label: 'Full Stack', value: 'Full Stack' },
          { label: 'Fun/Sandbox', value: 'Fun/Sandbox' },
        ],
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        placeholder: 'Enter project description',
        validation: {
          maxLength: 1000,
        },
      },
      {
        name: 'liveUrl',
        label: 'Live URL',
        type: 'url',
        required: false,
        placeholder: 'https://example.com',
      },

      {
        name: 'repoUrl',
        label: 'Repository URL (optional)',
        type: 'url',
        required: false,
        placeholder: 'https://git.example.com/owner/repo',
      },
      {
        name: 'techStack',
        label: 'Tech Stack',
        type: 'multiselect',
        required: false,
        options: [
          { label: 'React', value: 'React' },
          { label: 'TypeScript', value: 'TypeScript' },
          { label: 'Node.js', value: 'Node.js' },
          { label: 'MongoDB', value: 'MongoDB' },
          { label: 'Next.js', value: 'Next.js' },
          { label: 'Tailwind CSS', value: 'Tailwind CSS' },
          { label: 'Python', value: 'Python' },
          { label: 'Django', value: 'Django' },
          { label: 'PostgreSQL', value: 'PostgreSQL' },
          { label: 'Docker', value: 'Docker' },
        ],
      },
      {
        name: 'duration',
        label: 'Duration',
        type: 'text',
        required: false,
        placeholder: 'e.g., 3-4 months',
      },
      {
        name: 'teamSize',
        label: 'Team Size',
        type: 'text',
        required: false,
        placeholder: 'e.g., Solo project / 2 developers',
      },
      {
        name: 'importance',
        label: 'Importance',
        type: 'select',
        required: false,
        options: [
          { label: 'High', value: 'high' },
          { label: 'Medium', value: 'medium' },
          { label: 'Low', value: 'low' },
        ],
      },
      // Removed duplicate 'category' field (duplicate keys caused React warnings)
      {
        name: 'gradient',
        label: 'Card Gradient',
        type: 'select',
        required: false,
        options: [
          { label: 'Red 600 → Red 700', value: 'from-red-600 to-red-700' },
          { label: 'Gray 700 → Gray 800', value: 'from-gray-700 to-gray-800' },
          { label: 'Gray 800 → Gray 900', value: 'from-gray-800 to-gray-900' },
          { label: 'Blue 50 → Indigo 100', value: 'from-blue-50 to-indigo-100' },
          { label: 'Teal 400 → Yellow 200', value: 'from-teal-400 to-yellow-200' },
          { label: 'Red 500 → Orange 500', value: 'from-red-500 to-orange-500' },
          { label: 'Green 400 → Blue 400', value: 'from-green-400 to-blue-400' },
          { label: 'Purple 400 → Pink 400', value: 'from-purple-400 to-pink-400' },
          { label: 'Indigo 400 → Purple 400', value: 'from-indigo-400 to-purple-400' },
        ],
      },
      {
        name: 'hasPreview',
        label: 'Has Preview',
        type: 'checkbox',
        required: false,
      },
      {
        name: 'previewType',
        label: 'Preview Type',
        type: 'select',
        required: false,
        options: [
          { label: 'Image', value: 'image' },
          { label: 'Chart', value: 'chart' },
          { label: 'Dashboard', value: 'dashboard' },
          { label: 'Components', value: 'components' },
          { label: 'Visualization', value: 'visualization' },
          { label: 'E-commerce', value: 'ecommerce' },
          { label: 'Platform', value: 'platform' },
          { label: 'Game', value: 'game' },
          { label: 'Music', value: 'music' },
          { label: 'AR', value: 'ar' },
          { label: 'Other', value: 'other' },
        ],
      },
      {
        name: 'heroImageUrl',
        label: 'Hero Image',
        type: 'image',
        required: false,
        placeholder: 'Select or upload image',
      },
      {
        name: 'visibility',
        label: 'Visibility',
        type: 'select',
        required: true,
        validation: { minLength: 1 },
        options: [
          { label: 'Public', value: 'public' },
          { label: 'Private', value: 'private' },
        ],
      },
    ],
  },

  experience: {
    id: 'experience',
    title: 'Experience',
    description: 'Add or update work experience',
    submitText: 'Save Experience',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'title',
        label: 'Job Title',
        type: 'text',
        required: true,
        placeholder: 'Software Engineer',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'company',
        label: 'Company',
        type: 'text',
        required: true,
        placeholder: 'Company Name',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'location',
        label: 'Location',
        type: 'text',
        required: false,
        placeholder: 'City, Country',
      },
      {
        name: 'startDate',
        label: 'Start Date',
        type: 'date',
        required: true,
        validation: { minLength: 1 },
      },
      {
        name: 'endDate',
        label: 'End Date',
        type: 'date',
        required: false,
      },
      {
        name: 'current',
        label: 'Currently Working Here',
        type: 'checkbox',
        required: false,
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe your role and responsibilities',
        validation: {
          minLength: 1,
          maxLength: 1000,
        },
      },
      {
        name: 'technologies',
        label: 'Technologies Used',
        type: 'multiselect',
        required: false,
        options: [
          { label: 'React', value: 'React' },
          { label: 'TypeScript', value: 'TypeScript' },
          { label: 'Node.js', value: 'Node.js' },
          { label: 'MongoDB', value: 'MongoDB' },
          { label: 'Python', value: 'Python' },
          { label: 'Django', value: 'Django' },
          { label: 'PostgreSQL', value: 'PostgreSQL' },
          { label: 'AWS', value: 'AWS' },
          { label: 'Docker', value: 'Docker' },
          { label: 'Kubernetes', value: 'Kubernetes' },
        ],
      },
    ],
  },

  certification: {
    id: 'certification',
    title: 'Certification',
    description: 'Add or update certification',
    submitText: 'Save Certification',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'name',
        label: 'Certification Name',
        type: 'text',
        required: true,
        placeholder: 'AWS Certified Solutions Architect',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'issuer',
        label: 'Issuing Organization',
        type: 'text',
        required: true,
        placeholder: 'Amazon Web Services',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'issueDate',
        label: 'Issue Date',
        type: 'date',
        required: true,
      },
      {
        name: 'expiryDate',
        label: 'Expiry Date',
        type: 'date',
        required: false,
      },
      {
        name: 'credentialId',
        label: 'Credential ID',
        type: 'text',
        required: false,
        placeholder: 'ABC123456',
      },
      {
        name: 'credentialUrl',
        label: 'Credential URL',
        type: 'url',
        required: false,
        placeholder: 'https://verify.aws.com/credential',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        placeholder: 'Brief description of the certification',
      },
    ],
  },

  badge: {
    id: 'badge',
    title: 'Badge',
    description: 'Add or update achievement badge',
    submitText: 'Save Badge',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'name',
        label: 'Badge Name',
        type: 'text',
        required: true,
        placeholder: 'Top Contributor',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'issuer',
        label: 'Issuing Organization',
        type: 'text',
        required: true,
        placeholder: 'GitHub',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'issueDate',
        label: 'Issue Date',
        type: 'date',
        required: true,
      },
      {
        name: 'badgeUrl',
        label: 'Badge Image',
        type: 'image',
        required: false,
        placeholder: 'Select or upload image',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        placeholder: 'Description of the achievement',
      },
      {
        name: 'category',
        label: 'Category',
        type: 'text',
        required: false,
        placeholder: 'Open Source, Hackathon, etc.',
      },
    ],
  },

  technology: {
    id: 'technology',
    title: 'Technology',
    description: 'Add or update technology skill',
    submitText: 'Save Technology',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'name',
        label: 'Technology Name',
        type: 'text',
        required: true,
        placeholder: 'React',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'category',
        label: 'Category',
        type: 'select',
        required: true,
        options: [
          { label: 'Frontend/UI/UX', value: 'Frontend/UI/UX' },
          { label: 'Full Stack', value: 'Full Stack' },
          { label: 'AI Learning/Exploration', value: 'AI Learning/Exploration' },
          { label: 'Fun/Sandbox', value: 'Fun/Sandbox' },
          { label: 'Backend', value: 'backend' },
          { label: 'Database', value: 'database' },
          { label: 'DevOps', value: 'devops' },
          { label: 'Mobile', value: 'mobile' },
          { label: 'Other', value: 'other' },
        ],
        validation: {
          minLength: 1,
          maxLength: 50,
        },
      },
      {
        name: 'complexity',
        label: 'Proficiency Level',
        type: 'select',
        required: true,
        validation: { minLength: 1 },
        options: [
          { label: 'Beginner', value: 'Beginner' },
          { label: 'Intermediate', value: 'Intermediate' },
          { label: 'Advanced', value: 'Advanced' },
          { label: 'Expert', value: 'Expert' },
        ],
      },
      {
        name: 'icon',
        label: 'Technology Icon',
        type: 'image',
        required: false,
        placeholder: 'Select or upload image',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        placeholder: 'Brief description of your experience with this technology',
      },
      {
        name: 'yearsOfExperience',
        label: 'Years of Experience',
        type: 'number',
        required: false,
        placeholder: '3',
        validation: {
          min: 0,
        },
      },
      {
        name: 'learningSource',
        label: 'Learning Source',
        type: 'text',
        required: false,
        placeholder: 'Udemy, YouTube, etc.',
      },
      {
        name: 'confidenceLevel',
        label: 'Confidence Level',
        type: 'number',
        required: false,
        placeholder: '1-10',
      },
      {
        name: 'color',
        label: 'Color',
        type: 'text',
        required: false,
        placeholder: 'Color',
      },
    ],
  },

  profile: {
    id: 'profile',
    title: 'Profile',
    description: 'Update your profile information',
    submitText: 'Save Profile',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'firstName',
        label: 'First Name',
        type: 'text',
        required: true,
        placeholder: 'John',
        validation: {
          minLength: 1,
          maxLength: 50,
        },
      },
      {
        name: 'lastName',
        label: 'Last Name',
        type: 'text',
        required: true,
        placeholder: 'Doe',
        validation: {
          minLength: 1,
          maxLength: 50,
        },
      },
      {
        name: 'email',
        label: 'Email',
        type: 'email',
        required: true,
        placeholder: 'john.doe@example.com',
      },
      {
        name: 'title',
        label: 'Professional Title',
        type: 'text',
        required: true,
        placeholder: 'Full Stack Developer',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'bio',
        label: 'Bio',
        type: 'textarea',
        required: true,
        placeholder: 'Tell us about yourself',
        validation: {
          minLength: 1,
          maxLength: 500,
        },
      },
      {
        name: 'location',
        label: 'Location',
        type: 'text',
        required: false,
        placeholder: 'San Francisco, CA',
      },
      {
        name: 'website',
        label: 'Website',
        type: 'url',
        required: false,
        placeholder: 'https://yourwebsite.com',
      },
      {
        name: 'github',
        label: 'GitHub',
        type: 'url',
        required: false,
        placeholder: 'https://github.com/username',
      },
      {
        name: 'linkedin',
        label: 'LinkedIn',
        type: 'url',
        required: false,
        placeholder: 'https://linkedin.com/in/username',
      },
      {
        name: 'twitter',
        label: 'Twitter',
        type: 'url',
        required: false,
        placeholder: 'https://twitter.com/username',
      },
    ],
  },

  message: {
    id: 'message',
    title: 'Message',
    description: 'Reply to a message',
    submitText: 'Send Reply',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        validation: { minLength: 1 },
        options: [
          { label: 'Unread', value: 'unread' },
          { label: 'Read', value: 'read' },
          { label: 'Replied', value: 'replied' },
          { label: 'Archived', value: 'archived' },
        ],
      },
    ],
  },

  resume: {
    id: 'resume',
    title: 'Resume',
    description: 'Upload or update resume',
    submitText: 'Save Resume',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'title',
        label: 'Resume Title',
        type: 'text',
        required: true,
        placeholder: 'Software Engineer Resume',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        placeholder: 'Brief description of this resume version',
      },
      {
        name: 'fileUrl',
        label: 'File URL',
        type: 'url',
        required: true,
        validation: { minLength: 1 },
        placeholder: 'https://example.com/resume.pdf',
      },
      {
        name: 'fileName',
        label: 'File Name',
        type: 'text',
        required: true,
        placeholder: 'resume.pdf',
      },
      {
        name: 'fileSize',
        label: 'File Size (bytes)',
        type: 'number',
        required: true,
        placeholder: '1024000',
        validation: {
          min: 1,
        },
      },
      {
        name: 'isPublic',
        label: 'Public Resume',
        type: 'checkbox',
        required: false,
      },
    ],
  },
}

// experience

export const getFormConfig = (entityType: string): Form | null => {
  return formConfigs[entityType] || null
}

export const getAvailableForms = (): string[] => {
  return Object.keys(formConfigs)
}
