import { Form } from './schemas'

// Form configurations for each entity type
export const formConfigs: Record<string, Form> = {
  project: {
    id: 'project',
    title: 'Project',
    description: 'Create or update a project',
    submitText: 'Save Project',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        required: true,
        placeholder: 'Enter project title',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'slug',
        label: 'Slug',
        type: 'text',
        required: true,
        placeholder: 'project-slug',
        validation: {
          minLength: 1,
          maxLength: 100,
          pattern: '^[a-z0-9-]+$',
        },
      },
      {
        name: 'kind',
        label: 'Project Type',
        type: 'select',
        required: true,
        validation: { minLength: 1 },
        options: [
          { label: 'Learning', value: 'learning' },
          { label: 'Frontend', value: 'frontend' },
          { label: 'Full Stack', value: 'fullstack' },
          { label: 'AI Learning', value: 'ai_learning' },
        ],
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        placeholder: 'Enter project description',
        validation: {
          maxLength: 1000,
        },
      },
      {
        name: 'techStack',
        label: 'Tech Stack',
        type: 'multiselect',
        required: false,
        options: [
          { label: 'React', value: 'React' },
          { label: 'TypeScript', value: 'TypeScript' },
          { label: 'Node.js', value: 'Node.js' },
          { label: 'MongoDB', value: 'MongoDB' },
          { label: 'Next.js', value: 'Next.js' },
          { label: 'Tailwind CSS', value: 'Tailwind CSS' },
          { label: 'Python', value: 'Python' },
          { label: 'Django', value: 'Django' },
          { label: 'PostgreSQL', value: 'PostgreSQL' },
          { label: 'Docker', value: 'Docker' },
        ],
      },
      {
        name: 'tags',
        label: 'Tags',
        type: 'multiselect',
        required: false,
        options: [
          { label: 'Web Development', value: 'web-development' },
          { label: 'Mobile App', value: 'mobile-app' },
          { label: 'API', value: 'api' },
          { label: 'Database', value: 'database' },
          { label: 'UI/UX', value: 'ui-ux' },
          { label: 'Machine Learning', value: 'machine-learning' },
          { label: 'DevOps', value: 'devops' },
          { label: 'Testing', value: 'testing' },
        ],
      },
      {
        name: 'heroImageUrl',
        label: 'Hero Image URL',
        type: 'url',
        required: false,
        placeholder: 'https://example.com/image.png',
      },
      {
        name: 'visibility',
        label: 'Visibility',
        type: 'select',
        required: true,
        validation: { minLength: 1 },
        options: [
          { label: 'Public', value: 'public' },
          { label: 'Private', value: 'private' },
        ],
      },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        validation: { minLength: 1 },
        options: [
          { label: 'Draft', value: 'draft' },
          { label: 'Published', value: 'published' },
          { label: 'Archived', value: 'archived' },
        ],
      },
    ],
  },

  experience: {
    id: 'experience',
    title: 'Experience',
    description: 'Add or update work experience',
    submitText: 'Save Experience',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'title',
        label: 'Job Title',
        type: 'text',
        required: true,
        placeholder: 'Software Engineer',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'company',
        label: 'Company',
        type: 'text',
        required: true,
        placeholder: 'Company Name',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'location',
        label: 'Location',
        type: 'text',
        required: false,
        placeholder: 'City, Country',
      },
      {
        name: 'startDate',
        label: 'Start Date',
        type: 'date',
        required: true,
        validation: { minLength: 1 },
      },
      {
        name: 'endDate',
        label: 'End Date',
        type: 'date',
        required: false,
      },
      {
        name: 'current',
        label: 'Currently Working Here',
        type: 'checkbox',
        required: false,
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe your role and responsibilities',
        validation: {
          minLength: 1,
          maxLength: 1000,
        },
      },
      {
        name: 'technologies',
        label: 'Technologies Used',
        type: 'multiselect',
        required: false,
        options: [
          { label: 'React', value: 'React' },
          { label: 'TypeScript', value: 'TypeScript' },
          { label: 'Node.js', value: 'Node.js' },
          { label: 'MongoDB', value: 'MongoDB' },
          { label: 'Python', value: 'Python' },
          { label: 'Django', value: 'Django' },
          { label: 'PostgreSQL', value: 'PostgreSQL' },
          { label: 'AWS', value: 'AWS' },
          { label: 'Docker', value: 'Docker' },
          { label: 'Kubernetes', value: 'Kubernetes' },
        ],
      },
    ],
  },

  certification: {
    id: 'certification',
    title: 'Certification',
    description: 'Add or update certification',
    submitText: 'Save Certification',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'name',
        label: 'Certification Name',
        type: 'text',
        required: true,
        placeholder: 'AWS Certified Solutions Architect',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'issuer',
        label: 'Issuing Organization',
        type: 'text',
        required: true,
        placeholder: 'Amazon Web Services',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'issueDate',
        label: 'Issue Date',
        type: 'date',
        required: true,
      },
      {
        name: 'expiryDate',
        label: 'Expiry Date',
        type: 'date',
        required: false,
      },
      {
        name: 'credentialId',
        label: 'Credential ID',
        type: 'text',
        required: false,
        placeholder: 'ABC123456',
      },
      {
        name: 'credentialUrl',
        label: 'Credential URL',
        type: 'url',
        required: false,
        placeholder: 'https://verify.aws.com/credential',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        placeholder: 'Brief description of the certification',
      },
    ],
  },

  badge: {
    id: 'badge',
    title: 'Badge',
    description: 'Add or update achievement badge',
    submitText: 'Save Badge',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'name',
        label: 'Badge Name',
        type: 'text',
        required: true,
        placeholder: 'Top Contributor',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'issuer',
        label: 'Issuing Organization',
        type: 'text',
        required: true,
        placeholder: 'GitHub',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'issueDate',
        label: 'Issue Date',
        type: 'date',
        required: true,
      },
      {
        name: 'badgeUrl',
        label: 'Badge Image URL',
        type: 'url',
        required: false,
        placeholder: 'https://example.com/badge.png',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        placeholder: 'Description of the achievement',
      },
      {
        name: 'category',
        label: 'Category',
        type: 'text',
        required: false,
        placeholder: 'Open Source, Hackathon, etc.',
      },
    ],
  },

  technology: {
    id: 'technology',
    title: 'Technology',
    description: 'Add or update technology skill',
    submitText: 'Save Technology',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'name',
        label: 'Technology Name',
        type: 'text',
        required: true,
        placeholder: 'React',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'category',
        label: 'Category',
        type: 'select',
        required: true,
        options: [
          { label: 'Frontend', value: 'frontend' },
          { label: 'Backend', value: 'backend' },
          { label: 'Database', value: 'database' },
          { label: 'DevOps', value: 'devops' },
          { label: 'Mobile', value: 'mobile' },
          { label: 'AI/ML', value: 'ai-ml' },
          { label: 'Other', value: 'other' },
        ],
        validation: {
          minLength: 1,
          maxLength: 50,
        },
      },
      {
        name: 'proficiency',
        label: 'Proficiency Level',
        type: 'select',
        required: true,
        validation: { minLength: 1 },
        options: [
          { label: 'Beginner', value: 'beginner' },
          { label: 'Intermediate', value: 'intermediate' },
          { label: 'Advanced', value: 'advanced' },
          { label: 'Expert', value: 'expert' },
        ],
      },
      {
        name: 'iconUrl',
        label: 'Technology Icon URL',
        type: 'url',
        required: false,
        placeholder: 'https://example.com/icon.png',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        placeholder: 'Brief description of your experience with this technology',
      },
      {
        name: 'yearsOfExperience',
        label: 'Years of Experience',
        type: 'number',
        required: false,
        placeholder: '3',
        validation: {
          min: 0,
        },
      },
    ],
  },

  profile: {
    id: 'profile',
    title: 'Profile',
    description: 'Update your profile information',
    submitText: 'Save Profile',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'firstName',
        label: 'First Name',
        type: 'text',
        required: true,
        placeholder: 'John',
        validation: {
          minLength: 1,
          maxLength: 50,
        },
      },
      {
        name: 'lastName',
        label: 'Last Name',
        type: 'text',
        required: true,
        placeholder: 'Doe',
        validation: {
          minLength: 1,
          maxLength: 50,
        },
      },
      {
        name: 'email',
        label: 'Email',
        type: 'email',
        required: true,
        placeholder: 'john.doe@example.com',
      },
      {
        name: 'title',
        label: 'Professional Title',
        type: 'text',
        required: true,
        placeholder: 'Full Stack Developer',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'bio',
        label: 'Bio',
        type: 'textarea',
        required: true,
        placeholder: 'Tell us about yourself',
        validation: {
          minLength: 1,
          maxLength: 500,
        },
      },
      {
        name: 'location',
        label: 'Location',
        type: 'text',
        required: false,
        placeholder: 'San Francisco, CA',
      },
      {
        name: 'website',
        label: 'Website',
        type: 'url',
        required: false,
        placeholder: 'https://yourwebsite.com',
      },
      {
        name: 'github',
        label: 'GitHub',
        type: 'url',
        required: false,
        placeholder: 'https://github.com/username',
      },
      {
        name: 'linkedin',
        label: 'LinkedIn',
        type: 'url',
        required: false,
        placeholder: 'https://linkedin.com/in/username',
      },
      {
        name: 'twitter',
        label: 'Twitter',
        type: 'url',
        required: false,
        placeholder: 'https://twitter.com/username',
      },
    ],
  },

  message: {
    id: 'message',
    title: 'Message',
    description: 'Reply to a message',
    submitText: 'Send Reply',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        validation: { minLength: 1 },
        options: [
          { label: 'Unread', value: 'unread' },
          { label: 'Read', value: 'read' },
          { label: 'Replied', value: 'replied' },
          { label: 'Archived', value: 'archived' },
        ],
      },
    ],
  },

  resume: {
    id: 'resume',
    title: 'Resume',
    description: 'Upload or update resume',
    submitText: 'Save Resume',
    cancelText: 'Cancel',
    fields: [
      {
        name: 'title',
        label: 'Resume Title',
        type: 'text',
        required: true,
        placeholder: 'Software Engineer Resume',
        validation: {
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        placeholder: 'Brief description of this resume version',
      },
      {
        name: 'fileUrl',
        label: 'File URL',
        type: 'url',
        required: true,
        validation: { minLength: 1 },
        placeholder: 'https://example.com/resume.pdf',
      },
      {
        name: 'fileName',
        label: 'File Name',
        type: 'text',
        required: true,
        placeholder: 'resume.pdf',
      },
      {
        name: 'fileSize',
        label: 'File Size (bytes)',
        type: 'number',
        required: true,
        placeholder: '1024000',
        validation: {
          min: 1,
        },
      },
      {
        name: 'isPublic',
        label: 'Public Resume',
        type: 'checkbox',
        required: false,
      },
    ],
  },
}

export const getFormConfig = (entityType: string): Form | null => {
  return formConfigs[entityType] || null
}

export const getAvailableForms = (): string[] => {
  return Object.keys(formConfigs)
}
