import type { ApiResponse } from '@/types/api'
import type { PortfolioCategoryMap } from '@/types/portfolio'

export async function fetchPortfolioData(): Promise<ApiResponse<PortfolioCategoryMap>> {
  // Dummy data mirrored from design, centralized for future DB replacement
  const data: PortfolioCategoryMap = {
    'AI Learning/Exploration': [
      {
        id: 'ai-1',
        title: 'Neural Style Transfer App',
        description:
          'Advanced deep learning application that transforms artistic styles to photographs using convolutional neural networks. Features real-time processing with GPU acceleration, custom model training pipeline, and interactive web interface. Supports multiple style transfer algorithms including Gatys et al. and Johnson et al. methods. Includes batch processing capabilities, style interpolation, and comprehensive model performance analytics.',
        techStack: ['TensorFlow', 'Python', 'FastAPI', 'React', 'WebGL'],
        duration: '3-4 months',
        teamSize: 'Solo project',
        importance: 'high',
        liveUrl: '#',
        repoUrl: '#',
        gradient: 'from-red-600 to-red-700',
        hasPreview: true,
        previewType: 'image',
        category: 'AI Learning/Exploration',
      },
      {
        id: 'ai-2',
        title: 'LLM Fine-tuning Pipeline',
        description:
          'Automated pipeline for fine-tuning large language models on custom datasets with distributed training and model evaluation metrics.',
        techStack: ['PyTorch', 'Transformers', 'Docker', 'Kubernetes'],
        duration: '2-3 months',
        teamSize: '2 developers',
        importance: 'high',
        liveUrl: '#',
        repoUrl: '#',
        gradient: 'from-gray-800 to-gray-900',
        hasPreview: true,
        previewType: 'chart',
        category: 'AI Learning/Exploration',
      },
      {
        id: 'ai-3',
        title: 'Computer Vision Dashboard',
        description:
          'Real-time object detection and tracking system with analytics dashboard for retail environments.',
        techStack: ['OpenCV', 'YOLO', 'Flask', 'MongoDB'],
        duration: '1-2 months',
        teamSize: 'Solo project',
        importance: 'medium',
        liveUrl: '#',
        repoUrl: '#',
        gradient: 'from-gray-700 to-gray-800',
        hasPreview: true,
        previewType: 'dashboard',
        category: 'AI Learning/Exploration',
      },
    ],
    'Frontend/UI/UX': [
      {
        id: 'fe-1',
        title: 'Design System Library',
        description:
          'Comprehensive design system featuring 50+ accessible components built with TypeScript and extensive Storybook documentation. Includes theming system, responsive utilities, animation library, and automated testing suite. Components follow WCAG 2.1 guidelines with full keyboard navigation support. Features automated visual regression testing, comprehensive prop validation, and seamless integration with popular frameworks.',
        techStack: ['React', 'TypeScript', 'Storybook', 'Tailwind CSS'],
        duration: '2-3 months',
        teamSize: '3 designers, 2 developers',
        importance: 'high',
        liveUrl: '#',
        repoUrl: '#',
        gradient: 'from-red-600 to-red-700',
        hasPreview: true,
        previewType: 'components',
        category: 'Frontend/UI/UX',
      },
      {
        id: 'fe-2',
        title: 'Interactive Data Viz Platform',
        description:
          'Dynamic data visualization platform with custom chart components and real-time updates.',
        techStack: ['D3.js', 'React', 'WebSocket', 'Three.js'],
        duration: '1-2 months',
        teamSize: 'Solo project',
        importance: 'medium',
        liveUrl: '#',
        repoUrl: '#',
        gradient: 'from-gray-700 to-gray-800',
        hasPreview: true,
        previewType: 'visualization',
        category: 'Frontend/UI/UX',
      },
      {
        id: 'fe-3',
        title: 'Mobile-First E-commerce',
        description:
          'Progressive web app for e-commerce with offline capabilities and seamless checkout experience.',
        techStack: ['Next.js', 'PWA', 'Stripe API', 'Tailwind'],
        duration: '3-4 weeks',
        teamSize: '2 developers',
        importance: 'medium',
        liveUrl: '#',
        repoUrl: '#',
        gradient: 'from-gray-800 to-gray-900',
        hasPreview: true,
        previewType: 'ecommerce',
        category: 'Frontend/UI/UX',
      },
    ],
    'Full Stack': [
      {
        id: 'fs-1',
        title: 'Real-time Collaboration Platform',
        description:
          'Slack-like application with real-time messaging, file sharing, video calls, and project management features.',
        techStack: ['Node.js', 'Socket.io', 'PostgreSQL', 'Redis', 'React'],
        duration: '4-6 months',
        teamSize: '4 developers',
        importance: 'high',
        liveUrl: '#',
        repoUrl: '#',
        gradient: 'from-red-600 to-red-700',
        hasPreview: true,
        previewType: 'platform',
        category: 'Full Stack',
      },
      {
        id: 'fs-2',
        title: 'Microservices API Gateway',
        description:
          'Scalable microservices architecture with API gateway, service discovery, and comprehensive monitoring.',
        techStack: ['Docker', 'Kubernetes', 'Node.js', 'MongoDB', 'RabbitMQ'],
        duration: '2-3 months',
        teamSize: '3 developers',
        importance: 'high',
        liveUrl: '#',
        repoUrl: '#',
        gradient: 'from-gray-800 to-gray-900',
        category: 'Full Stack',
      },
    ],
    'Fun/Sandbox': [
      {
        id: 'fun-1',
        title: '3D Web Game Engine',
        description:
          'Browser-based 3D game engine with physics simulation, particle effects, and multiplayer capabilities.',
        techStack: ['Three.js', 'Cannon.js', 'WebRTC', 'WebGL'],
        duration: '2-3 months',
        teamSize: 'Solo project',
        importance: 'medium',
        liveUrl: '#',
        repoUrl: '#',
        gradient: 'from-gray-700 to-gray-800',
        hasPreview: true,
        previewType: 'game',
        category: 'Fun/Sandbox',
      },
      {
        id: 'fun-2',
        title: 'Music Visualization Tool',
        description:
          'Interactive music visualizer with WebAudio API featuring responsive animations and custom shaders.',
        techStack: ['WebAudio API', 'WebGL', 'JavaScript', 'GLSL'],
        duration: '3-4 weeks',
        teamSize: 'Solo project',
        importance: 'low',
        liveUrl: '#',
        repoUrl: '#',
        gradient: 'from-gray-700 to-gray-800',
        hasPreview: true,
        previewType: 'music',
        category: 'Fun/Sandbox',
      },
      {
        id: 'fun-3',
        title: 'AR Business Card',
        description:
          'Augmented reality business card using WebAR with 3D models and interactive elements.',
        techStack: ['AR.js', 'Three.js', 'WebXR', 'A-Frame'],
        duration: '1-2 weeks',
        teamSize: 'Solo project',
        importance: 'low',
        liveUrl: '#',
        repoUrl: '#',
        gradient: 'from-gray-700 to-gray-800',
        hasPreview: true,
        previewType: 'ar',
        category: 'Fun/Sandbox',
      },
    ],
  }

  return Promise.resolve({ success: true, data: data })
}
